# Site settings
name: Sonal Jain
title: Sonal Jain | Product Manager
description: Focused on building technology enabled products centered around addressing customer needs
url: https://sonal1771.github.io/
baseurl: ''
email: brittany.chiang@gmail.com
cover: https://sonal1771.github.io/img/og.png
logo: https://sonal1771.github.io/img/emojis/technologist.png
resume: https://sonal1771.github.io/resume.pdf
social:
  - title: email
    url: mailto:sonal1771@gmail.com
  - title: twitter
    url: https://twitter.com/sonal1771
  - title: instagram
    url: https://instagram.com//mini_canvasart/
  - title: behance
    url: https://www.behance.net/sonaljain4
  - title: github
    url: https://github.com/sonal1771
  - title: linkedin
    url: https://www.linkedin.com/in/json

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
